/* automatically generated by rust-bindgen 0.59.1 */

#[allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod root {
    #[allow(unused_imports)]
    use self::super::root;
    pub mod std {
        #[allow(unused_imports)]
        use self::super::super::root;
        pub mod __fs {
            #[allow(unused_imports)]
            use self::super::super::super::root;
        }
    }
    pub type size_t = ::std::os::raw::c_ulong;
    pub mod lczero {
        #[allow(unused_imports)]
        use self::super::super::root;
        pub mod rust {
            #[allow(unused_imports)]
            use self::super::super::super::root;
            pub type RustBackend = ::std::os::raw::c_void;
            #[repr(C)]
            #[derive(Debug, Copy, Clone)]
            pub struct RustMove {
                pub from: u8,
                pub to: u8,
                pub promotion: ::std::os::raw::c_char,
            }
            #[test]
            fn bindgen_test_layout_RustMove() {
                assert_eq!(
                    ::std::mem::size_of::<RustMove>(),
                    3usize,
                    concat!("Size of: ", stringify!(RustMove))
                );
                assert_eq!(
                    ::std::mem::align_of::<RustMove>(),
                    1usize,
                    concat!("Alignment of ", stringify!(RustMove))
                );
                assert_eq!(
                    unsafe { &(*(::std::ptr::null::<RustMove>())).from as *const _ as usize },
                    0usize,
                    concat!(
                        "Offset of field: ",
                        stringify!(RustMove),
                        "::",
                        stringify!(from)
                    )
                );
                assert_eq!(
                    unsafe { &(*(::std::ptr::null::<RustMove>())).to as *const _ as usize },
                    1usize,
                    concat!(
                        "Offset of field: ",
                        stringify!(RustMove),
                        "::",
                        stringify!(to)
                    )
                );
                assert_eq!(
                    unsafe { &(*(::std::ptr::null::<RustMove>())).promotion as *const _ as usize },
                    2usize,
                    concat!(
                        "Offset of field: ",
                        stringify!(RustMove),
                        "::",
                        stringify!(promotion)
                    )
                );
            }
            #[repr(C)]
            #[derive(Debug, Copy, Clone)]
            pub struct RustMoveHistory {
                pub moves: *mut root::lczero::rust::RustMove,
                pub length: root::size_t,
            }
            #[test]
            fn bindgen_test_layout_RustMoveHistory() {
                assert_eq!(
                    ::std::mem::size_of::<RustMoveHistory>(),
                    16usize,
                    concat!("Size of: ", stringify!(RustMoveHistory))
                );
                assert_eq!(
                    ::std::mem::align_of::<RustMoveHistory>(),
                    8usize,
                    concat!("Alignment of ", stringify!(RustMoveHistory))
                );
                assert_eq!(
                    unsafe {
                        &(*(::std::ptr::null::<RustMoveHistory>())).moves as *const _ as usize
                    },
                    0usize,
                    concat!(
                        "Offset of field: ",
                        stringify!(RustMoveHistory),
                        "::",
                        stringify!(moves)
                    )
                );
                assert_eq!(
                    unsafe {
                        &(*(::std::ptr::null::<RustMoveHistory>())).length as *const _ as usize
                    },
                    8usize,
                    concat!(
                        "Offset of field: ",
                        stringify!(RustMoveHistory),
                        "::",
                        stringify!(length)
                    )
                );
            }
            #[repr(C)]
            #[derive(Debug, Copy, Clone)]
            pub struct RustEvaluationRequest {
                pub history: root::lczero::rust::RustMoveHistory,
                pub starting_fen: *const ::std::os::raw::c_char,
            }
            #[test]
            fn bindgen_test_layout_RustEvaluationRequest() {
                assert_eq!(
                    ::std::mem::size_of::<RustEvaluationRequest>(),
                    24usize,
                    concat!("Size of: ", stringify!(RustEvaluationRequest))
                );
                assert_eq!(
                    ::std::mem::align_of::<RustEvaluationRequest>(),
                    8usize,
                    concat!("Alignment of ", stringify!(RustEvaluationRequest))
                );
                assert_eq!(
                    unsafe {
                        &(*(::std::ptr::null::<RustEvaluationRequest>())).history as *const _
                            as usize
                    },
                    0usize,
                    concat!(
                        "Offset of field: ",
                        stringify!(RustEvaluationRequest),
                        "::",
                        stringify!(history)
                    )
                );
                assert_eq!(
                    unsafe {
                        &(*(::std::ptr::null::<RustEvaluationRequest>())).starting_fen as *const _
                            as usize
                    },
                    16usize,
                    concat!(
                        "Offset of field: ",
                        stringify!(RustEvaluationRequest),
                        "::",
                        stringify!(starting_fen)
                    )
                );
            }
            #[repr(C)]
            #[derive(Debug, Copy, Clone)]
            pub struct RustEvaluation {
                pub p_: [f32; 1858usize],
                pub q_: f32,
                pub d_: f32,
                pub m_: f32,
            }
            #[test]
            fn bindgen_test_layout_RustEvaluation() {
                assert_eq!(
                    ::std::mem::size_of::<RustEvaluation>(),
                    7444usize,
                    concat!("Size of: ", stringify!(RustEvaluation))
                );
                assert_eq!(
                    ::std::mem::align_of::<RustEvaluation>(),
                    4usize,
                    concat!("Alignment of ", stringify!(RustEvaluation))
                );
                assert_eq!(
                    unsafe { &(*(::std::ptr::null::<RustEvaluation>())).p_ as *const _ as usize },
                    0usize,
                    concat!(
                        "Offset of field: ",
                        stringify!(RustEvaluation),
                        "::",
                        stringify!(p_)
                    )
                );
                assert_eq!(
                    unsafe { &(*(::std::ptr::null::<RustEvaluation>())).q_ as *const _ as usize },
                    7432usize,
                    concat!(
                        "Offset of field: ",
                        stringify!(RustEvaluation),
                        "::",
                        stringify!(q_)
                    )
                );
                assert_eq!(
                    unsafe { &(*(::std::ptr::null::<RustEvaluation>())).d_ as *const _ as usize },
                    7436usize,
                    concat!(
                        "Offset of field: ",
                        stringify!(RustEvaluation),
                        "::",
                        stringify!(d_)
                    )
                );
                assert_eq!(
                    unsafe { &(*(::std::ptr::null::<RustEvaluation>())).m_ as *const _ as usize },
                    7440usize,
                    concat!(
                        "Offset of field: ",
                        stringify!(RustEvaluation),
                        "::",
                        stringify!(m_)
                    )
                );
            }
            extern "C" {
                pub fn new_backend(
                    str_: *const ::std::os::raw::c_char,
                ) -> *mut root::lczero::rust::RustBackend;
            }
            extern "C" {
                pub fn evaluate(
                    responses: *mut root::lczero::rust::RustEvaluation,
                    requests: *const root::lczero::rust::RustEvaluationRequest,
                    num_requests: root::size_t,
                    t: *const root::lczero::rust::RustBackend,
                );
            }
            extern "C" {
                pub fn delete_backend(t: *mut root::lczero::rust::RustBackend);
            }
            extern "C" {
                pub fn move_to_policy_index(m: root::lczero::rust::RustMove, black: bool) -> u16;
            }
        }
    }
}
